//
//  Cities.swift
//  uiSearch
//
//  Created by Varun Mishra on 7/25/15.
//  Copyright (c) 2015 Bamboo Tree. All rights reserved.
//

import UIKit

var cityList: Cities = Cities()

class Cities {
    var arrayOfCities = ["New York, NY",
        "Los Angeles, CA",
        "Chicago, IL",
        "Houston, TX",
        "Phoenix, AZ",
        "Philadelphia, PA",
        "San Antonio, TX",
        "San Diego, CA",
        "Dallas, TX",
        "San Jose, CA",
        "Detroit, MI",
        "San Francisco, CA",
        "Jacksonville, FL",
        "Indianapolis, IN",
        "Austin, TX",
        "Columbus, OH",
        "Fort Worth, TX",
        "Charlotte, NC",
        "Memphis, TN",
        "Boston, MA",
        "Baltimore, MD",
        "El Paso, TX",
        "Seattle, WA",
        "Denver, CO",
        "Nashville-Davidson, TN",
        "Milwaukee, WI",
        "Washington, District of Columbia",
        "Las Vegas, NV",
        "Louisville/Jefferson County, KY",
        "Portland, OR",
        "Oklahoma City, OK",
        "Tucson, AZ",
        "Atlanta, GA",
        "Albuquerque, NM",
        "Kansas City, MO",
        "Fresno, CA",
        "Mesa, AZ",
        "Sacramento, CA",
        "Long Beach, CA",
        "Omaha, NE",
        "Virginia Beach, VA",
        "Miami, FL",
        "Cleveland, OH",
        "Oakland, CA",
        "Raleigh, NC",
        "Colorado Springs, CO",
        "Tulsa, OK",
        "Minneapolis, MN",
        "Arlington, TX",
        "Honolulu, HI",
        "Wichita, KS",
        "St. Louis, MO",
        "New Orleans, LA",
        "Tampa, FL",
        "Santa Ana, CA",
        "Anaheim, CA",
        "Cincinnati, OH",
        "Bakersfield, CA",
        "Aurora, CO",
        "Toledo, OH",
        "Pittsburgh, PA",
        "Riverside, CA",
        "Lexington-Fayette, KY",
        "Stockton, CA",
        "Corpus Christi, TX",
        "Anchorage, AK",
        "St. Paul, MN",
        "Newark, NJ",
        "Plano, TX",
        "Buffalo, NY",
        "Henderson, NV",
        "Fort Wayne, IN",
        "Greensboro, NC",
        "Lincoln, NE",
        "Glendale, AZ",
        "Chandler, AZ",
        "St. Petersburg, FL",
        "Jersey City, NJ",
        "Scottsdale, AZ",
        "Orlando, FL",
        "Madison, WI",
        "Norfolk, VA",
        "Birmingham, AL",
        "Winston-Salem, NC",
        "Durham, NC",
        "Laredo, TX",
        "Lubbock, TX",
        "Baton Rouge, LA",
        "North Las Vegas, NV",
        "Chula Vista, CA",
        "Chesapeake, VA",
        "Gilbert, AZ",
        "Garland, TX",
        "Reno, NV",
        "Hialeah, FL",
        "Arlington, VA",
        "Irvine, CA",
        "Rochester, NY",
        "Akron, OH",
        "Boise City, ID",
        "Irving, TX",
        "Fremont, CA",
        "Richmond, VA",
        "Spokane, WA",
        "Modesto, CA",
        "Montgomery, AL",
        "Yonkers, NY",
        "Des Moines, IA",
        "Tacoma, WA",
        "Shreveport, LA",
        "San Bernardino, CA",
        "Fayetteville, NC",
        "Glendale, CA",
        "Augusta-Richmond County, GA",
        "Grand Rapids, MI",
        "Huntington Beach, CA",
        "Mobile, AL",
        "Newport News, VA",
        "Little Rock, AR",
        "Moreno Valley, CA",
        "Columbus, GA",
        "Amarillo, TX",
        "Fontana, CA",
        "Oxnard, CA",
        "Knoxville, TN",
        "Fort Lauderdale, FL",
        "Salt Lake City, UT",
        "Worcester, MA",
        "Huntsville, AL",
        "Tempe, AZ",
        "Brownsville, TX",
        "Jackson, MS",
        "Overland Park, KS",
        "Aurora, IL",
        "Oceanside, CA",
        "Tallahassee, FL",
        "Providence, RI",
        "Rancho Cucamonga, CA",
        "Ontario, CA",
        "Chattanooga, TN",
        "Santa Clarita, CA",
        "Garden Grove, CA",
        "Vancouver, WA",
        "Grand Prairie, TX",
        "Peoria, AZ",
        "Sioux Falls, SD",
        "Springfield, MO",
        "Santa Rosa, CA",
        "Rockford, IL",
        "Springfield, MA",
        "Salem, OR",
        "Port St. Lucie, FL",
        "Cape Coral, FL",
        "Dayton, OH",
        "Eugene, OR",
        "Pomona, CA",
        "Corona, CA",
        "Alexandria, VA",
        "Joliet, IL",
        "Pembroke Pines, FL",
        "Paterson, NJ",
        "Pasadena, TX",
        "Lancaster, CA",
        "Hayward, CA",
        "Salinas, CA",
        "Hampton, VA",
        "Palmdale, CA",
        "Pasadena, CA",
        "Naperville, IL",
        "Kansas City, KS",
        "Hollywood, FL",
        "Lakewood, CO",
        "Torrance, CA",
        "Escondido, CA",
        "Fort Collins, CO",
        "Syracuse, NY",
        "Bridgeport, CT",
        "Orange, CA",
        "Cary, NC",
        "Elk Grove, CA",
        "Savannah, GA",
        "Sunnyvale, CA",
        "Warren, MI",
        "Mesquite, TX",
        "Fullerton, CA",
        "McAllen, TX",
        "Columbia, SC",
        "Carrollton, TX",
        "Cedar Rapids, IA",
        "McKinney, TX",
        "Sterling Heights, MI",
        "Bellevue, WA",
        "Coral Springs, FL",
        "Waco, TX",
        "Elizabeth, NJ",
        "West Valley City, UT",
        "Clarksville, TN",
        "Topeka, KS",
        "Hartford, CT",
        "Thousand Oaks, CA",
        "New Haven, CT",
        "Denton, TX",
        "Concord, CA",
        "Visalia, CA",
        "Olathe, KS",
        "El Monte, CA",
        "Independence, MO",
        "Stamford, CT",
        "Simi Valley, CA",
        "Provo, UT",
        "Killeen, TX",
        "Springfield, IL",
        "Thornton, CO",
        "Abilene, TX",
        "Gainesville, FL",
        "Evansville, IN",
        "Roseville, CA",
        "Charleston, SC",
        "Peoria, IL",
        "Athens-Clarke County, GA",
        "Lafayette, LA",
        "Vallejo, CA",
        "Lansing, MI",
        "Ann Arbor, MI",
        "Inglewood, CA",
        "Santa Clara, CA",
        "Flint, MI",
        "Victorville, CA",
        "Costa Mesa, CA",
        "Beaumont, TX",
        "Miami Gardens, FL",
        "Manchester, NH",
        "Westminster, CO",
        "Miramar, FL",
        "Norman, OK",
        "Cambridge, MA",
        "Midland, TX",
        "Arvada, CO",
        "Allentown, PA",
        "Elgin, IL",
        "Waterbury, CT",
        "Downey, CA",
        "Clearwater, FL",
        "Billings, MT",
        "West Covina, CA",
        "Round Rock, TX",
        "Murfreesboro, TN",
        "Lewisville, TX",
        "West Jordan, UT",
        "Pueblo, CO",
        "San Buenaventura (Ventura), CA",
        "Lowell, MA",
        "South Bend, IN",
        "Fairfield, CA",
        "Erie, PA",
        "Rochester, MN",
        "High Point, NC",
        "Richardson, TX",
        "Richmond, CA",
        "Burbank, CA",
        "Berkeley, CA",
        "Pompano Beach, FL",
        "Norwalk, CA",
        "Frisco, TX",
        "Columbia, MO",
        "Gresham, OR",
        "Daly City, CA",
        "Green Bay, WI",
        "Wilmington, NC",
        "Davenport, IA",
        "Wichita Falls, TX",
        "Antioch, CA",
        "Palm Bay, FL",
        "Odessa, TX",
        "Centennial, CO",
        "Boulder, CO",
        "West Palm Beach, FL",
        "Everett, WA",
        "Portsmouth, VA",
        "Temecula, CA",
        "Tyler, TX",
        "Rialto, CA",
        "Carlsbad, CA",
        "Kenosha, WI",
        "Murrieta, CA",
        "North Charleston, SC",
        "Sandy, UT",
        "South Gate, CA",
        "Gary, IN",
        "Fargo, ND",
        "Hillsboro, OR",
        "Orem, UT",
        "Surprise, AZ",
        "Broken Arrow, OK",
        "Mission Viejo, CA",
        "Roanoke, VA",
        "El Cajon, CA",
        "Compton, CA",
        "Albany, NY",
        "Lakeland, FL",
        "Brockton, MA",
        "Las Cruces, NM",
        "Beaverton, OR",
        "Clovis, CA",
        "Tuscaloosa, AL",
        "San Mateo, CA",
        "Greeley, CO",
        "Macon, GA",
        "Vista, CA",
        "Carson, CA",
        "San Angelo, TX",
        "Lawrence, KS",
        "Vacaville, CA",
        "Davie, FL",
        "Lawton, OK",
        "Yuma, AZ",
        "New Bedford, MA",
        "Quincy, MA",
        "Fall River, MA",
        "Waukegan, IL",
        "Redding, CA",
        "Sunrise, FL",
        "Westminster, CA",
        "Sparks, NV",
        "Livonia, MI",
        "Longmont, CO",
        "Miami Beach, FL",
        "Roswell, GA",
        "Santa Monica, CA",
        "Nashua, NH",
        "Lynn, MA",
        "Spokane Valley, WA",
        "Santa Maria, CA",
        "College Station, TX",
        "Lee's Summit, MO",
        "Boca Raton, FL",
        "Santa Barbara, CA",
        "Pearland, TX",
        "Hesperia, CA",
        "Yakima, WA",
        "Federal Way, WA",
        "Sandy Springs, GA",
        "Fort Smith, AR",
        "Kent, WA",
        "Avondale, AZ",
        "Alhambra, CA",
        "Indio, CA",
        "Plantation, FL",
        "Chico, CA",
        "Warwick, RI",
        "Citrus Heights, CA",
        "Newton, MA",
        "Dearborn, MI",
        "Duluth, MN",
        "Allen, TX",
        "Hawthorne, CA",
        "Norwalk, CT",
        "Suffolk, VA",
        "Deltona, FL",
        "Ogden, UT",
        "Trenton, NJ",
        "Bloomington, MN",
        "Sioux City, IA",
        "Chino, CA",
        "Rio Rancho, NM",
        "Racine, WI",
        "Whittier, CA",
        "Greenville, NC",
        "Sugar Land, TX",
        "Newport Beach, CA",
        "Nampa, ID",
        "Edmond, OK",
        "Livermore, CA",
        "Reading, PA",
        "San Marcos, CA",
        "Troy, MI",
        "Jacksonville, NC",
        "Champaign, IL",
        "Cranston, RI",
        "Cicero, IL",
        "Bellingham, WA",
        "Buena Park, CA",
        "Danbury, CT",
        "Tracy, CA",
        "O'Fallon, MO",
        "Camden, NJ",
        "Farmington Hills, MI",
        "San Leandro, CA",
        "Canton, OH",
        "Clifton, NJ",
        "Lakewood, CA",
        "Longview, TX",
        "Evanston, IL",
        "Melbourne, FL",
        "Bend, OR",
        "Westland, MI",
        "Parma, OH",
        "Fayetteville, AR",
        "Baldwin Park, CA",
        "Asheville, NC",
        "Hammond, IN",
        "Somerville, MA",
        "Merced, CA",
        "St. Joseph, MO",
        "Decatur, IL",
        "Lake Forest, CA",
        "Albany, GA",
        "Southfield, MI",
        "Napa, CA",
        "Deerfield Beach, FL",
        "Missouri City, TX",
        "Bryan, TX",
        "Redwood City, CA",
        "New Rochelle, NY",
        "Bloomington, IL",
        "Santa Fe, NM",
        "Lynchburg, VA",
        "Chino Hills, CA",
        "Medford, OR",
        "Largo, FL",
        "Palm Coast, FL",
        "Arlington Heights, IL",
        "Bethlehem, PA",
        "Wilmington, DE",
        "Hoover, AL",
        "Upland, CA",
        "Gastonia, NC",
        "Bellflower, CA",
        "Union City, CA",
        "Plymouth, MN",
        "Kalamazoo, MI",
        "St. George, UT",
        "Tustin, CA",
        "Youngstown, OH",
        "Edinburg, TX",
        "Mountain View, CA",
        "Brooklyn Park, MN",
        "Pawtucket, RI",
        "Scranton, PA",
        "Bloomington, IN",
        "Hemet, CA",
        "League City, TX",
        "Lake Charles, LA",
        "Schaumburg, IL",
        "Alameda, CA",
        "Fishers, IN",
        "Appleton, WI",
        "Bolingbrook, IL",
        "Baytown, TX",
        "Gulfport, MS",
        "Wyoming, MI",
        "Lawrence, MA",
        "New Britain, CT",
        "Lorain, OH",
        "Flower Mound, TX",
        "Apple Valley, CA",
        "Redlands, CA",
        "Lynwood, CA",
        "Boynton Beach, FL",
        "Carmel, IN",
        "Rock Hill, SC",
        "Rochester Hills, MI",
        "Iowa City, IA",
        "Mission, TX",
        "Missoula, MT",
        "Mount Vernon, NY",
        "Turlock, CA",
        "Meridian, ID",
        "Springdale, AR",
        "Waukesha, WI",
        "Milpitas, CA",
        "Kenner, LA",
        "Kennewick, WA",
        "Folsom, CA",
        "Muncie, IN",
        "Pleasanton, CA",
        "Dothan, AL",
        "Lauderhill, FL",
        "Concord, NC",
        "St. Cloud, MN",
        "Rapid City, SD",
        "Passaic, NJ",
        "Marietta, GA",
        "Waterloo, IA",
        "Layton, UT",
        "Redondo Beach, CA",
        "Palatine, IL",
        "Skokie, IL",
        "Mount Pleasant, SC",
        "Eau Claire, WI",
        "Pontiac, MI",
        "Pharr, TX",
        "Loveland, CO",
        "Jonesboro, AR",
        "Yorba Linda, CA",
        "North Richland Hills, TX",
        "Lafayette, IN",
        "St. Charles, MO",
        "Manteca, CA",
        "Harlingen, TX",
        "East Orange, NJ",
        "Pittsburg, CA",
        "Delray Beach, FL",
        "Laguna Niguel, CA",
        "Fort Myers, FL",
        "Cedar Park, TX",
        "Oshkosh, WI",
        "Eagan, MN",
        "Walnut Creek, CA",
        "Camarillo, CA",
        "Weston, FL",
        "Daytona Beach, FL",
        "Jackson, TN",
        "Goodyear, AZ",
        "Maple Grove, MN",
        "Auburn, WA",
        "Janesville, WI",
        "Bossier City, LA",
        "Victoria, TX",
        "Johnson City, TN",
        "Portland, ME",
        "Davis, CA",
        "Rancho Cordova, CA",
        "Pico Rivera, CA",
        "South San Francisco, CA",
        "Hamilton, OH",
        "Kissimmee, FL",
        "Eden Prairie, MN",
        "Coon Rapids, MN",
        "Rockville, MD",
        "Springfield, OH",
        "Warner Robins, GA",
        "Renton, WA",
        "Union City, NJ",
        "Johns Creek, GA",
        "Greenville, SC",
        "Shawnee, KS",
        "Montebello, CA",
        "San Clemente, CA",
        "Encinitas, CA",
        "Yuba City, CA",
        "Haverhill, MA",
        "Monterey Park, CA",
        "Schenectady, NY",
        "Lodi, CA",
        "Bismarck, ND",
        "Bristol, CT",
        "Huntington Park, CA",
        "Franklin, TN",
        "Flagstaff, AZ",
        "Waltham, MA",
        "West Allis, WI",
        "Council Bluffs, IA",
        "St. Clair Shores, MI",
        "Palo Alto, CA",
        "North Little Rock, AR",
        "Temple, TX",
        "Gaithersburg, MD",
        "Terre Haute, IN",
        "Homestead, FL",
        "Tamarac, FL",
        "Frederick, MD",
        "Rocky Mount, NC",
        "Conway, AR",
        "La Habra, CA",
        "Great Falls, MT",
        "Taylor, MI",
        "Vineland, NJ",
        "Meriden, CT",
        "Tinley Park, IL",
        "Burnsville, MN",
        "Taylorsville, UT",
        "Rogers, AR",
        "Pasco, WA",
        "Grand Junction, CO",
        "Conroe, TX",
        "Gardena, CA",
        "Bayonne, NJ",
        "Utica, NY",
        "North Miami, FL",
        "Auburn, AL",
        "Lakewood, WA",
        "Tulare, CA",
        "Cheyenne, WY",
        "White Plains, NY",
        "Woodbury, MN",
        "Springfield, OR",
        "Dubuque, IA",
        "Midwest City, OK",
        "Anderson, IN",
        "Royal Oak, MI",
        "Diamond Bar, CA",
        "West Des Moines, IA",
        "Des Plaines, IL",
        "Santa Cruz, CA",
        "Rowlett, TX",
        "Port Arthur, TX",
        "Madera, CA",
        "Ames, IA",
        "Bowling Green, KY",
        "Decatur, AL",
        "St. Peters, MO",
        "Blaine, MN",
        "Arcadia, CA",
        "Perris, CA",
        "Galveston, TX",
        "Malden, MA",
        "National City, CA",
        "Lakeville, MN",
        "Broomfield, CO",
        "Chicopee, MA",
        "San Rafael, CA",
        "New Braunfels, TX",
        "Fountain Valley, CA",
        "Blue Springs, MO",
        "Taunton, MA",
        "Owensboro, KY",
        "Lake Havasu City, AZ",
        "Medford, MA",
        "Ocala, FL",
        "La Mesa, CA",
        "Lancaster, PA",
        "Santee, CA",
        "Idaho Falls, ID",
        "Woodland, CA",
        "Saginaw, MI",
        "Orland Park, IL",
        "Petaluma, CA",
        "Carson City, NV",
        "Pocatello, ID",
        "Paramount, CA",
        "Elyria, OH",
        "Casper, WY",
        "South Jordan, UT",
        "Wellington, FL",
        "Milford, CT",
        "Novi, MI",
        "Wheaton, IL",
        "Port Orange, FL",
        "Margate, FL",
        "Cupertino, CA",
        "Rosemead, CA",
        "North Port, FL",
        "Bradenton, FL",
        "Hempstead, NY",
        "Moore, OK",
        "Pensacola, FL",
        "Hoffman Estates, IL",
        "Hattiesburg, MS",
        "Rocklin, CA",
        "Chapel Hill, NC",
        "Kettering, OH",
        "Novato, CA",
        "Bowie, MD",
        "Euless, TX",
        "San Marcos, TX",
        "Oak Park, IL",
        "Elkhart, IN",
        "Mount Prospect, IL",
        "West Haven, CT",
        "Oak Lawn, IL",
        "Manhattan, KS",
        "Delano, CA",
        "Normal, IL",
        "Shoreline, WA",
        "Cathedral City, CA",
        "Redmond, WA",
        "Valdosta, GA",
        "Porterville, CA",
        "Sarasota, FL",
        "Mentor, OH",
        "Palm Desert, CA",
        "Battle Creek, MI",
        "Buckeye, AZ",
        "Peabody, MA",
        "Revere, MA",
        "Monroe, LA",
        "Middletown, OH",
        "New Brunswick, NJ",
        "Burlington, NC",
        "Alpharetta, GA",
        "Corvallis, OR",
        "Niagara Falls, NY",
        "La Crosse, WI",
        "Grand Forks, ND",
        "Cerritos, CA",
        "Lake Elsinore, CA",
        "Grapevine, TX",
        "Cuyahoga Falls, OH",
        "Watsonville, CA",
        "Bellevue, NE",
        "Highland, CA",
        "Sanford, FL",
        "Georgetown, TX",
        "Dearborn Heights, MI",
        "Minnetonka, MN",
        "Smyrna, GA",
        "Jupiter, FL",
        "Florissant, MO",
        "Coconut Creek, FL",
        "Colton, CA",
        "Pine Bluff, AR",
        "Charleston, WV",
        "Lakewood, OH",
        "Joplin, MO",
        "Gilroy, CA",
        "Apple Valley, MN",
        "Mishawaka, IN",
        "Hanford, CA",
        "Yucaipa, CA",
        "Placentia, CA",
        "Poway, CA",
        "Bedford, TX",
        "Palm Beach Gardens, FL",
        "La Mirada, CA",
        "Glendora, CA",
        "Brentwood, CA",
        "Berwyn, IL",
        "San Ramon, CA",
        "Logan, UT",
        "Rancho Santa Margarita, CA",
        "Mansfield, OH",
        "Tigard, OR",
        "Downers Grove, IL",
        "Huntington, WV",
        "Lehi, UT",
        "Alexandria, LA",
        "Wilson, NC",
        "Perth Amboy, NJ",
        "East Providence, RI",
        "Kirkland, WA",
        "Albany, OR",
        "Middletown, CT",
        "Hendersonville, TN",
        "Greenwood, IN",
        "DeSoto, TX",
        "Palm Springs, CA",
        "Lenexa, KS",
        "Bartlett, TN",
        "Enid, OK",
        "West Sacramento, CA",
        "Sheboygan, WI",
        "Kentwood, MI",
        "Troy, NY",
        "Richland, WA",
        "Harrisburg, PA",
        "Newark, OH",
        "Mansfield, TX",
        "Cypress, CA",
        "Pinellas Park, FL",
        "Euclid, OH",
        "Grand Island, NE",
        "Covina, CA",
        "Roseville, MI",
        "Azusa, CA",
        "Edina, MN",
        "Murray, UT",
        "West New York, NJ",
        "Roswell, NM",
        "Portage, MI",
        "Plainfield, NJ",
        "Elmhurst, IL",
        "Altoona, PA",
        "Barnstable Town, MA",
        "Glenview, IL",
        "Salina, KS",
        "Stillwater, OK",
        "Olympia, WA",
        "Chesterfield, MO",
        "Biloxi, MS",
        "DeKalb, IL",
        "Castle Rock, CO",
        "Menifee, CA",
        "East Lansing, MI",
        "St. Louis Park, MN",
        "Cleveland Heights, OH",
        "Kokomo, IN",
        "Southaven, MS",
        "Wauwatosa, WI",
        "Cedar Hill, TX",
        "Summerville, SC",
        "Harrisonburg, VA",
        "Huntersville, NC",
        "Kingsport, TN",
        "Parker, CO",
        "The Colony, TX",
        "La Quinta, CA",
        "Maricopa, AZ",
        "Bell Gardens, CA",
        "Dublin, CA",
        "Titusville, FL",
        "Bountiful, UT",
        "Lincoln, CA",
        "Coral Gables, FL",
        "Binghamton, NY",
        "Danville, VA",
        "Methuen, MA",
        "Lawrence, IN",
        "San Luis Obispo, CA",
        "Commerce City, CO",
        "Oro Valley, AZ",
        "Texas City, TX",
        "Freeport, NY",
        "Casa Grande, AZ",
        "Coeur d'Alene, ID",
        "Attleboro, MA",
        "East Point, GA",
        "Farmington, NM",
        "Kannapolis, NC",
        "Warren, OH",
        "Woonsocket, RI",
        "Caldwell, ID",
        "Draper, UT",
        "Sierra Vista, AZ",
        "Covington, KY",
        "Moline, IL",
        "Noblesville, IN",
        "Blacksburg, VA",
        "Bonita Springs, FL",
        "Buffalo Grove, IL",
        "Hackensack, NJ",
        "Lombard, IL",
        "Bartlett, IL",
        "Prescott, AZ",
        "Twin Falls, ID",
        "Pflugerville, TX",
        "Ceres, CA",
        "Ankeny, IA",
        "North Lauderdale, FL",
        "Fort Pierce, FL",
        "Oakland Park, FL",
        "Fairfield, OH",
        "Concord, NH",
        "Pittsfield, MA",
        "Strongsville, OH",
        "Fond du Lac, WI",
        "Sammamish, WA",
        "Leominster, MA",
        "Sayreville, NJ",
        "Charlottesville, VA",
        "Newark, CA",
        "Crystal Lake, IL",
        "Fitchburg, MA",
        "Westfield, MA",
        "Lacey, WA",
        "Beavercreek, OH",
        "Aliso Viejo, CA",
        "Danville, CA",
        "Hickory, NC",
        "San Bruno, CA",
        "Salem, MA",
        "Jefferson City, MO",
        "Belleville, IL",
        "North Miami Beach, FL",
        "El Centro, CA",
        "Germantown, TN",
        "Lompoc, CA",
        "Littleton, CO",
        "Hoboken, NJ",
        "Wilkes-Barre, PA",
        "Rancho Palos Verdes, CA",
        "Leesburg, VA",
        "Rohnert Park, CA",
        "Haltom City, TX",
        "Midland, MI",
        "Hutchinson, KS",
        "Edmonds, WA",
        "Bullhead City, AZ",
        "La Puente, CA",
        "Riverton, UT",
        "York, PA",
        "Holyoke, MA",
        "Spartanburg, SC",
        "Columbus, IN",
        "Shelton, CT",
        "San Gabriel, CA",
        "Cleveland, TN",
        "Coachella, CA",
        "Quincy, IL",
        "Keller, TX",
        "Carol Stream, IL",
        "Hagerstown, MD",
        "Muskogee, OK",
        "Urbana, IL",
        "Altamonte Springs, FL",
        "State College, PA",
        "Madison, AL",
        "Smyrna, TN",
        "Wylie, TX",
        "Meridian, MS",
        "Hot Springs, AR",
        "Coppell, TX",
        "Collierville, TN",
        "Atlantic City, NJ",
        "Beverly, MA",
        "Linden, NJ",
        "Dublin, OH",
        "Bozeman, MT",
        "New Berlin, WI",
        "Muskegon, MI",
        "Brookfield, WI",
        "Goose Creek, SC",
        "Hurst, TX",
        "Woburn, MA",
        "Hallandale Beach, FL",
        "Campbell, CA",
        "Calexico, CA",
        "Apopka, FL",
        "Cedar Falls, IA",
        "Urbandale, IA",
        "Burlington, VT",
        "Morgan Hill, CA",
        "Marlborough, MA",
        "Prescott Valley, AZ",
        "Brea, CA",
        "Wausau, WI",
        "Culver City, CA",
        "Sumter, SC",
        "Sherman, TX",
        "Goldsboro, NC",
        "Everett, MA",
        "Temple City, CA",
        "Florence, AL",
        "Huntsville, TX",
        "Rock Island, IL",
        "Carpentersville, IL",
        "Romeoville, IL",
        "Pacifica, CA",
        "San Jacinto, CA",
        "Stanton, CA",
        "Ormond Beach, FL",
        "Puyallup, WA",
        "Lima, OH",
        "Cape Girardeau, MO",
        "Lake Oswego, OR",
        "Monrovia, CA",
        "New Albany, IN",
        "Chelsea, MA",
        "Portage, IN",
        "Lancaster, OH",
        "Brentwood, TN",
        "Texarkana, TX",
        "Chester, PA",
        "Franklin, WI",
        "Streamwood, IL",
        "Huber Heights, OH",
        "Addison, IL",
        "Westerville, OH",
        "Riviera Beach, FL",
        "Annapolis, MD",
        "Bentonville, AR",
        "Park Ridge, IL",
        "Moorhead, MN",
        "Rockwall, TX",
        "Maplewood, MN",
        "Gadsden, AL",
        "Hanover Park, IL",
        "Moorpark, CA",
        "Del Rio, TX",
        "Plainfield, IL",
        "Findlay, OH",
        "Panama City, FL",
        "Norwich, CT",
        "Calumet City, IL",
        "Richmond, IN",
        "Manhattan Beach, CA",
        "Beloit, WI",
        "Dover, DE",
        "Bell, CA",
        "Kearny, NJ",
        "Manassas, VA",
        "Mankato, MN",
        "Longview, WA",
        "Duncanville, TX",
        "Greenfield, WI",
        "Tupelo, MS",
        "Valley Stream, NY",
        "Montclair, CA",
        "Fort Lee, NJ",
        "University City, MO",
        "Roy, UT",
        "Minot, ND",
        "Lancaster, TX",
        "Burleson, TX",
        "Keizer, OR",
        "Bartlesville, OK",
        "Rome, GA",
        "Lake Worth, FL",
        "Alamogordo, NM",
        "Dunedin, FL",
        "Wheeling, IL",
        "West Hollywood, CA",
        "Long Beach, NY",
        "Dana Point, CA",
        "Marion, OH",
        "Gainesville, GA",
        "Martinez, CA",
        "Claremont, CA",
        "Torrington, CT",
        "Cottonwood Heights, UT"]
}